### ISSUE TITLE
New Logo for AndelaMedManager

### ISSUE THREAD

**Issue by familqasimov** [jumaallan/AndelaMedManager#2]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-2](https://user-images.githubusercontent.com/36432269/39399532-6208a8f0-4b30-11e8-8206-fff971163490.png)

**Comment by jumaallan** [comment]
Hi @familqasimov 
This looks super awesome! I will be happy to use it, and give you credits also for the good work. Feel free to send a PR, it would be more than welcome 💯

**Comment by familqasimov** [comment]
Thank you @jumaallan for merge the logo
